import React, { useState } from 'react';

export default function Reports() {
  const [reportType, setReportType] = useState('website');
  const [targetReference, setTargetReference] = useState('');
  const [feedbackDescription, setFeedbackDescription] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    // Payload for client report / feedback
    const reportData = {
      report_type: reportType,
      target_reference: targetReference,
      feedback_description: feedbackDescription,
    };

    try {
      const response = await fetch('/api/reports/client-feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(reportData),
      });
      if (response.ok) {
        setSubmitted(true);
        setTargetReference('');
        setFeedbackDescription('');
        setTimeout(() => setSubmitted(false), 4000);
      }
    } catch (error) {
      console.error('Error submitting report:', error);
    }
  };

  return (
    <div className="p-6">
      <div className="bg-white rounded-lg shadow-sm border border-gray-100 p-6">
        <div className="mb-6">
          <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
            <span>📋</span> Security Reports
          </h2>
          <p className="text-sm text-gray-500">Automated system threat summary generated by backend</p>
        </div>

        {/* Existing Threat Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-5">
            <h3 className="text-sm font-semibold text-blue-600 uppercase tracking-wider mb-1">Primary Threat Vector</h3>
            <p className="text-gray-800 font-medium">Brute Force Authentication / SSH Attempts</p>
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-lg p-5">
            <h3 className="text-sm font-semibold text-green-600 uppercase tracking-wider mb-1">Rule Engine Status</h3>
            <p className="text-gray-800 font-medium">Active - Real-time Log Stream Monitoring Enabled</p>
          </div>
        </div>
      </div>

      {/* NEW: Client Reporting & Feedback Section */}
      <div className="mt-6 bg-white rounded-lg shadow-sm border border-gray-100 p-6">
        <div className="mb-4">
          <h3 className="text-lg font-bold text-gray-800">Client Reporting & Feedback</h3>
          <p className="text-sm text-gray-500">Submit issues regarding website development, IP addresses, security anomalies, or general feedback.</p>
        </div>

        {submitted && (
          <div className="mb-4 p-3 bg-green-50 border border-green-200 text-green-700 text-sm rounded-md">
            Report and feedback submitted successfully!
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-gray-600 uppercase mb-1">Issue Category</label>
              <select 
                value={reportType} 
                onChange={(e) => setReportType(e.target.value)}
                className="w-full text-sm border border-gray-300 rounded-md p-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"
              >
                <option value="website">Website Development Issue</option>
                <option value="ip_address">IP Address / Network Concern</option>
                <option value="security">Security Vulnerability</option>
                <option value="general_feedback">General Feedback</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 uppercase mb-1">Target / Reference (e.g., URL or IP)</label>
              <input 
                type="text" 
                value={targetReference}
                onChange={(e) => setTargetReference(e.target.value)}
                placeholder="e.g., 192.168.1.50 or /login-page" 
                className="w-full text-sm border border-gray-300 rounded-md p-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                required
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-600 uppercase mb-1">Description & Feedback</label>
            <textarea 
              rows="3" 
              value={feedbackDescription}
              onChange={(e) => setFeedbackDescription(e.target.value)}
              placeholder="Provide detailed information regarding the report or feedback..." 
              className="w-full text-sm border border-gray-300 rounded-md p-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"
              required
            ></textarea>
          </div>

          <div className="flex justify-end">
            <button 
              type="submit" 
              className="bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold px-5 py-2 rounded-md transition duration-150"
            >
              Submit Report
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}